import { useCallback, useMemo, useState } from "react";

import { WEBMCP_TOOLS } from "../../webmcp/tools";
import { canonicalJsonStringify } from "../../webmcp/utils";
import { useWebMcp } from "../../webmcp/WebMcpProvider";

const SAMPLE_ARGS: Record<string, any> = {
  "clawdeals.deals_search": { limit: 1 },
  "clawdeals.deals_get": { deal_id: "00000000-0000-4000-a000-000000000123" },
  "clawdeals.listings_search": { limit: 1, sort: "recent" },
  "clawdeals.listings_get": { listing_id: "00000000-0000-4000-a000-000000000123" },
  "clawdeals.approvals_list": { limit: 5 },
  "clawdeals.approvals_get": { approval_id: "00000000-0000-4000-a000-000000000123" },
  "clawdeals.listings_create_draft": {
    title: "Draft listing (WebMCP)",
    description: "Generated by WebMCP tool. Contact: test@example.com",
    category: "electronics",
    condition: "GOOD",
    price_amount_minor: 4999,
    currency: "EUR"
  },
  "clawdeals.approvals_resolve": {
    approval_id: "00000000-0000-4000-a000-000000000123",
    decision: "APPROVE",
    note: "Approved via WebMCP demo"
  }
};

export default function WebMcpPage() {
  const { enabled, supported, registered, registeredToolNames, lastRegisterError, executeTool } = useWebMcp();
  const [toolName, setToolName] = useState<string>(() => WEBMCP_TOOLS[0]?.name || "clawdeals.deals_search");
  const [args, setArgs] = useState<string>(() => JSON.stringify(SAMPLE_ARGS[toolName] ?? {}, null, 2));
  const [running, setRunning] = useState(false);
  const [result, setResult] = useState<string>("");

  const tool = useMemo(() => WEBMCP_TOOLS.find((t) => t.name === toolName) || null, [toolName]);

  const handleSelect = useCallback((name: string) => {
    setToolName(name);
    setArgs(JSON.stringify(SAMPLE_ARGS[name] ?? {}, null, 2));
    setResult("");
  }, []);

  const handleRun = useCallback(async () => {
    if (!tool) return;
    setRunning(true);
    setResult("");
    try {
      const parsed = JSON.parse(args || "{}");
      const out = await executeTool(tool.name, parsed);
      setResult(JSON.stringify(out, null, 2));
    } catch (error: any) {
      setResult(
        JSON.stringify(
          { ok: false, error: { code: "ERROR", message: error?.message || "Execution failed", details: {} } },
          null,
          2
        )
      );
    } finally {
      setRunning(false);
    }
  }, [tool, args, executeTool]);

  const toolsJson = useMemo(() => {
    const list = WEBMCP_TOOLS.map((t) => ({
      name: t.name,
      scope: t.scope,
      requires_confirmation: t.requiresConfirmation,
      inputSchema: t.inputJsonSchema
    }));
    return canonicalJsonStringify(list);
  }, []);

  return (
    <div data-testid="webmcp-page" className="min-h-screen bg-bg text-text">
      <header className="border-b border-border bg-surface/80 backdrop-blur-sm sticky top-0 z-40">
        <div className="max-w-5xl mx-auto px-4 py-4 flex items-center justify-between">
          <div className="font-bold tracking-wider">
            <span className="text-primary">/ </span>DEV WEBMCP
          </div>
          <div className="text-xs font-mono text-subtle flex items-center gap-4">
            <span data-testid="webmcp-enabled">ENABLED: {enabled ? "YES" : "NO"}</span>
            <span data-testid="webmcp-supported">SUPPORTED: {supported ? "YES" : "NO"}</span>
            <span data-testid="webmcp-registered">REGISTERED: {registered ? "YES" : "NO"}</span>
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 py-8 space-y-6">
        <div className="border border-border bg-surface p-4 space-y-2">
          <div className="text-xs font-mono text-muted">
            Registered tools: <span data-testid="webmcp-registered-count">{registeredToolNames.length}</span>
          </div>
          {lastRegisterError ? (
            <div className="text-xs font-mono text-red-400">Register error: {lastRegisterError}</div>
          ) : null}
          <div className="text-[11px] font-mono text-subtle">
            This page can run tool handlers locally to validate strict schemas, confirmation gate, redaction, and output caps.
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="border border-border bg-surface p-4 space-y-3 md:col-span-1">
            <div className="text-[10px] font-mono uppercase tracking-widest text-subtle">Tools</div>
            <div className="space-y-2">
              {WEBMCP_TOOLS.map((t) => (
                <button
                  key={t.name}
                  onClick={() => handleSelect(t.name)}
                  className={`w-full text-left border px-3 py-2 rounded transition-colors ${
                    toolName === t.name
                      ? "border-primary/40 bg-primary/10"
                      : "border-border hover:border-border-strong"
                  }`}
                >
                  <div className="text-xs font-mono font-bold text-text">{t.name}</div>
                  <div className="text-[11px] font-mono text-muted">
                    scope={t.scope} confirm={t.requiresConfirmation ? "yes" : "no"}
                  </div>
                </button>
              ))}
            </div>
          </div>

          <div className="border border-border bg-surface p-4 space-y-3 md:col-span-2">
            <div className="flex items-center justify-between gap-3">
              <div className="space-y-1">
                <div className="text-[10px] font-mono uppercase tracking-widest text-subtle">Invoke</div>
                <div className="text-xs font-mono text-muted">{tool?.description || ""}</div>
              </div>
              <button
                disabled={!tool || running}
                onClick={handleRun}
                className="border border-primary px-4 py-2 text-xs font-mono font-bold uppercase text-primary hover:bg-primary hover:text-bg disabled:opacity-60"
              >
                {running ? "Running…" : "Run"}
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <label className="text-[10px] font-mono uppercase tracking-widest text-subtle" htmlFor="webmcp-args">
                  Args (JSON)
                </label>
                <textarea
                  id="webmcp-args"
                  value={args}
                  onChange={(e) => setArgs(e.target.value)}
                  name="args"
                  autoComplete="off"
                  spellCheck={false}
                  className="w-full min-h-[220px] text-xs font-mono bg-bg border border-border rounded p-2 text-text focus:border-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 focus-visible:ring-offset-2 focus-visible:ring-offset-bg"
                />
              </div>
              <div className="space-y-2">
                <div className="text-[10px] font-mono uppercase tracking-widest text-subtle">Result</div>
                <pre className="w-full min-h-[220px] text-xs font-mono bg-bg border border-border rounded p-2 text-text whitespace-pre-wrap break-words">
                  {result || "(no result yet)"}
                </pre>
              </div>
            </div>

            <div className="border border-border bg-bg/40 rounded p-3 space-y-2">
              <div className="text-[10px] font-mono uppercase tracking-widest text-subtle">Schemas</div>
              <pre className="text-[11px] font-mono text-muted whitespace-pre-wrap break-words">{toolsJson}</pre>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
