export const THREAD_WATCH_DEFAULT_TIMEOUT_MS = 25000;
export const THREAD_WATCH_MAX_TIMEOUT_MS = 30000;
export const THREAD_WATCH_POLL_INTERVAL_MS = 500;

export const THREAD_WATCH_DEFAULT_LIMIT = 50;
export const THREAD_WATCH_MAX_LIMIT = 200;

export const THREAD_WATCH_MAX_TYPES = 20;

