export const MAX_MATCHES_PER_DEAL = 2000;
export const WATCHLIST_BACKFILL_MAX_MATCHES = 200;

export const WATCHLIST_MATCH_EVENT_MAX_IDS = 20;

export const WATCHLIST_MATCHES_DEFAULT_LIMIT = 50;
export const WATCHLIST_MATCHES_MAX_LIMIT = 100;
